# You should write here protocol versions: https://wiki.vg/Protocol_version_numbers
versions:
  # Alert player that this version will be unsupported soon // Уведомляет игрока с версией из списка о скором прекращении поддержки его версии
  EOL:
    - 755
    - 756
  # Alert player that this version is unsupported and will be removed soon // Уведомляет игрока с версией из списка о том, что его версия больше не поддерживается
  Unsupported:
    - 735
    - 736
    - 751
    - 753
    - 754

messages:
  prefix: "&7[&6Уведомление&7] >>"
  EOL: "&eВаша версия скоро перестанет поддерживаться. Рекомендуем обновить клиент до более новой версии."
  Unsupported: "&cВаша версия больше не поддерживается, и может быть отключена в любой момент. Играйте на ней на свой страх и риск!"

# Delay of a message (in seconds). Minimum is 1 second // Задержка сообщение (в секундах). Минимум - 1 секунда
message-delay: 2

message-sound:
  enabled: true
  sound:
    EOL: "ENTITY_VILLAGER_HURT"
    Unsupported: "ENTITY_VILLAGER_DEATH"

# Just don't touch it, this will warn you about breaking config changes
config-version: 0
